### ISSUE TITLE
Exception caused by brackets

### ISSUE THREAD

**Issue by freddyheppell** [wingyplus/dockerletion#2]
Steps to reproduce:
1. Type brackets `()` in a comment

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [dockerletion](https://github.com/wingyplus/dockerletion) package, v0.1.0
### Stack Trace

Uncaught SyntaxError: Invalid regular expression: / (/: Unterminated group

```
At /Users/freddy/.atom/packages/dockerletion/lib/provider.coffee:8

SyntaxError: Invalid regular expression: / (/: Unterminated group
  at new RegExp (native)
  at String.match (native)
  at Object.<anonymous> (/Users/freddy/.atom/packages/dockerletion/lib/provider.coffee:8:112)
  at Object.module.exports.dockerAutocompleteProvider.getSuggestions (/Users/freddy/.atom/packages/dockerletion/lib/provider.coffee:22:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```
### Commands

```
     -4:43.3.0 core:save (atom-text-editor.editor.is-focused)
     -4:17.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:41.4.0 find-and-replace:show (div.settings-view.pane-item)
     -3:38.8.0 core:cancel (div.settings-view.pane-item)
     -3:30.9.0 core:confirm (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
  4x -3:20.8.0 core:backspace (atom-text-editor#editor.fontFamily.editor.mini.is-focused)
  2x -1:46.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -1:44.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:13.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:19 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:17.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:16.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:15.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:15.1.0 editor:newline (atom-text-editor.editor.is-focused)
  8x -0:09.9.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.14
dockerletion, v0.1.0
language-docker, v1.1.3
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by wingyplus** [comment]
Sorry for too late response. I will reproduce and fix it in next week. 

Thanks.
