### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: / [/: Unterminated character class

### ISSUE THREAD

**Issue by tPl0ch** [wingyplus/dockerletion#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Ubuntu 15.04
**Thrown From**: [dockerletion](https://github.com/wingyplus/dockerletion) package, v0.1.0
### Stack Trace

Uncaught SyntaxError: Invalid regular expression: / [/: Unterminated character class

```
At /home/tploch/.atom/packages/dockerletion/lib/provider.coffee:8

SyntaxError: Invalid regular expression: / [/: Unterminated character class
  at new RegExp (native)
  at String.match (native)
  at Object.<anonymous> (/home/tploch/.atom/packages/dockerletion/lib/provider.coffee:8:112)
  at Object.module.exports.dockerAutocompleteProvider.getSuggestions (/home/tploch/.atom/packages/dockerletion/lib/provider.coffee:22:12)
  at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
  at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
  at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```
### Commands

```
     -0:40.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:40 core:cut (atom-text-editor.editor.is-focused)
  3x -0:39.3.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:38.6.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:38.1.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  8x -0:37.7.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:35.5.0 core:cut (atom-text-editor.editor.is-focused)
     -0:33.4.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:33.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:32.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:32.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:31.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:31.5.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:28.3.0 core:cut (atom-text-editor.editor.is-focused)
  2x -0:26.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.5.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
dockerletion, v0.1.0
language-docker, v1.1.3

# Dev
No dev packages
```

**Comment by ThePooN** [comment]
Sad this most likely won't be fixed by the author. It's the only issue I got so far using this package.

**Comment by wingyplus** [comment]
Sorry for too late response. I will reproduce and fix it in next week. 

Thanks.
