### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: / (/: Unterminated group

### ISSUE THREAD

**Issue by pinage404** [wingyplus/dockerletion#4]
Hi,

First, thanks for this package =)

In a commented line (and only in commented line),
When i tape a "(" (who are automatically closed with a ")"), it raises this error :

**Atom Version**: 1.3.2
**System**: SolydK 8
**Thrown From**: [dockerletion](https://github.com/wingyplus/dockerletion) package, v0.1.0
### Stack Trace

Uncaught SyntaxError: Invalid regular expression: / (/: Unterminated group

```
At /home/pinage404/.atom/packages/dockerletion/lib/provider.coffee:8

SyntaxError: Invalid regular expression: / (/: Unterminated group
    at new RegExp (native)
    at String.match (native)
    at Object.<anonymous> (/home/pinage404/.atom/packages/dockerletion/lib/provider.coffee:8:112)
    at Object.module.exports.dockerAutocompleteProvider.getSuggestions (/home/pinage404/.atom/packages/dockerletion/lib/provider.coffee:8:20)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -8:27.3.0 application:new-file (atom-text-editor.editor.is-focused)
     -8:26.1.0 core:paste (atom-text-editor.editor.is-focused)
     -8:19.3.0 grammar-selector:show (atom-text-editor.editor)
  3x -1:43.5.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -1:13.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:08.4.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:32.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-monokai-soda"
    ],
    "disabledPackages": [
      "tool-bar-main",
      "autocomplete-atom-api",
      "update-package-dependencies",
      "markdown-format",
      "emmet",
      "spell-check",
      "open-on-github",
      "atom-terminal-panel",
      "markdown-scroll-sync",
      "autoclose-html",
      "build-tools",
      "toggle-markdown-task",
      "markdown-preview-opener"
    ],
    "projectHome": "~/Project",
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      ".directory"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
api-docs, v0.0.3
atom-beautify, v0.28.19
atom-material-ui, v0.8.0
atom-monokai-soda, v2.0.0
atom-notifier, v0.5.0
autocomplete-polymer, v0.2.4
build, v0.52.0
build-make, v0.7.0
dockerletion, v0.1.0
editor-stats, v0.17.0
editorconfig, v1.2.2
file-icons, v1.6.13
floobits, v0.30.0
git-log, v0.4.1
git-wip, v0.2.2
highlight-selected, v0.11.1
keyboard-localization, v1.4.13
language-babel, v2.6.3
language-docker, v1.1.6
language-fish-shell, v1.0.2
language-plantuml, v0.2.0
linter, v1.11.3
linter-cpplint, v1.0.1
linter-docker, v0.1.2
linter-markdown, v1.3.0
markdown-mindmap, v0.2.4
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.0
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
pigments, v0.19.5
plantuml-viewer, v0.7.0
polymer-atom, v0.0.8
polymerjs-snippets, v2.1.0
project-manager, v2.6.5
regex-railroad-diagram, v0.10.4
sync-settings, v0.6.0
tab-control, v0.6.8
tabs-to-spaces, v1.0.1
term3, v0.21.0
text-buffer, v7.1.0
tool-bar, v0.1.9
tool-bar-almighty, v0.5.0
tree-view-git-status, v0.2.2
vnc, v0.1.4

# Dev
No dev packages
```

**Comment by wingyplus** [comment]
Sorry for too late response. I will reproduce and fix it in next week. 

Thanks.
